"""IDFactory -- deterministic and random ID generators for MDLC artifacts.

All IDs generated by the platform use this factory to guarantee stable
prefixes, sortability, and no external state dependencies. Random IDs
use UUID4; deterministic IDs use SHA-256 over inputs.
"""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone


class IDFactory:
    """Generates typed, prefixed identifiers for all MDLC objects.

    IDs follow the pattern ``<prefix>-<short_uuid>`` for random IDs and
    ``<prefix>-<short_hash>`` for deterministic IDs.

    Examples:
        >>> idf = IDFactory()
        >>> idf.run_id()
        'run-3a4f8e2b1c'
        >>> idf.audit_id()
        'aud-7d9c1f4a2e'
    """

    @staticmethod
    def _short_uuid() -> str:
        return uuid.uuid4().hex[:10]

    @staticmethod
    def _short_hash(*parts: str) -> str:
        combined = "|".join(parts)
        return hashlib.sha256(combined.encode()).hexdigest()[:10]

    def run_id(self) -> str:
        """Generate a new random run identifier."""
        return f"run-{self._short_uuid()}"

    def session_id(self) -> str:
        """Generate a new random session identifier."""
        return f"sess-{self._short_uuid()}"

    def trace_id(self) -> str:
        """Generate a new random trace identifier."""
        return f"tr-{self._short_uuid()}"

    def audit_id(self) -> str:
        """Generate a new random audit event identifier."""
        return f"aud-{self._short_uuid()}"

    def review_id(self) -> str:
        """Generate a new random review identifier."""
        return f"rev-{self._short_uuid()}"

    def artifact_id(self, artifact_type: str, run_id: str, label: str = "") -> str:
        """Generate a deterministic artifact identifier from its type, run, and label.

        Args:
            artifact_type: Semantic artifact type (e.g. ``"model_binary"``).
            run_id: Run identifier this artifact belongs to.
            label: Optional label for disambiguation.

        Returns:
            Deterministic artifact ID string.
        """
        return f"art-{self._short_hash(artifact_type, run_id, label)}"

    def candidate_version_id(self, stage_id: str, run_id: str, index: int = 0) -> str:
        """Generate a deterministic candidate version identifier.

        Args:
            stage_id: Stage that produced this candidate.
            run_id: Run identifier.
            index: Candidate index within the stage (for multiple candidates).

        Returns:
            Deterministic candidate version ID string.
        """
        return f"cv-{self._short_hash(stage_id, run_id, str(index))}"

    def selection_id(self, candidate_version_id: str) -> str:
        """Generate a deterministic selection identifier for a version selection.

        Args:
            candidate_version_id: The selected candidate version ID.

        Returns:
            Deterministic selection ID string.
        """
        ts = datetime.now(timezone.utc).isoformat()
        return f"sel-{self._short_hash(candidate_version_id, ts)}"

    def findings_id(self, run_id: str, stage_id: str) -> str:
        """Generate a deterministic policy findings identifier.

        Args:
            run_id: Run identifier.
            stage_id: Stage at which policy was evaluated.

        Returns:
            Deterministic findings ID string.
        """
        ts = datetime.now(timezone.utc).isoformat()
        return f"fin-{self._short_hash(run_id, stage_id, ts)}"


# Module-level singleton -- use this for all platform ID generation.
id_factory = IDFactory()
